### ISSUE TITLE
Image needs to be updated because of Certificates.

### ISSUE THREAD

**Issue by phihub** [cw1/docker-webcron#2]
Lets Encrypt certificates cannot be verified because of outdated certificates in the image.

**Comment by rfilmyer** [comment]
I just ran into this as well, but this shouldn't make sense... the image is working off of `alpine:latest` and is a very, very thin shim over that.

**Comment by rfilmyer** [comment]
Sure enough, this is an Alpine Linux/Docker issue:  
https://github.com/alpinelinux/docker-alpine/issues/205
https://github.com/alpinelinux/docker-alpine/issues/206

**Comment by cw1** [comment]
As @rfilmyer mentioned the root cause is in the base image, therefor I'll close this issue. But thanks for mentioning.
